import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import Button from "~/components/Button";
import Loading from "~/components/Loading";
import RoundTop from "~/images/backgrounds/RoundTop";

export default function Index() {
    const { status } = useSession();
    const router = useRouter();
    return (
        <>
            <Head>
                <title>InCiteful</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="relative mx-auto  max-w-4xl px-4 pt-52">
                <RoundTop className="absolute left-1/2 top-0 -z-10 w-screen -translate-x-1/2" />
                <div className="">
                    <div className="mb-4 text-center  text-5xl">InCiteful</div>
                    <div className="text-center  text-4xl text-baltic-950">
                        Citations Made Easy.
                    </div>
                    <div className=" flex flex-col items-center gap-6 py-64 text-3xl">
                        Try it out!
                        {status === "loading" ? (
                            <Loading color="neutral" inline={false} />
                        ) : status === "authenticated" ? (
                            <div>
                                <Button
                                    className="w-36 text-xl"
                                    onClick={() => {
                                        void router.push("/dashboard");
                                    }}
                                    color="primary"
                                    text={"Dashboard"}
                                />
                            </div>
                        ) : (
                            <div className="flex flex-row justify-center gap-4">
                                <Button
                                    className=" text-xl"
                                    onClick={() => {
                                        void signIn("google");
                                    }}
                                    color="primary"
                                    text={"Sign in with Google"}
                                />
                                <Button
                                    className=" text-xl"
                                    onClick={() => {
                                        void signIn("discord");
                                    }}
                                    color="primary"
                                    text={"Sign in with Discord"}
                                />
                            </div>
                        )}
                    </div>
                    <div className="my-12 flex flex-row justify-between gap-6"></div>
                </div>
            </main>
        </>
    );
}
